
PART_IDS = [
    "Empty",
    "FAT12",
    "XENIX root",
    "XENIX usr",
    "FAT16",
    "Extended Partition",
    "FAT16B",
    "NTFS/exFAT/IFS/HPFS",
    "FAT/AIX/qny/Dell",
    "AIX/qnz/CFS/RBF",
    "OS2/CSP",
    "FAT32 (CHS)",
    "FAT32 (LBA)",
    "",
    "FAT16 (LBA)",
    "Extended Partition (LBA)",
    "",
    "FAT12/16",
    "BIOS/Service Related",
    "",
    "FAT12/FAT16/OFS",
    "Swap/OS2 Extended",
    "FAT16B",
    "IFS/HPFS/NTFS/exFAT",
    "Hibernation",
    "coS"
    "",
    "FAT32",
    "FAT32 (LBA)",
    "",
    "FAT16 (LBA)",
    "Extended Partition (LBA)",
    "WM Update XIP",
    "FSo2",
    "o2 EPT",
    "WM Boot XIP",
    "FAT12/16",
    "",
    "",
    "Windows RE",
    "Reserved",
    "SylStor"
]
